spring:
  data:
    mongodb:
      uri: mongodb://flashcards_user:flashcards_pass@localhost:27017/flashcards?authSource=flashcards
      database: flashcards
      auto-index-creation: true

  ai:
    openai:
      api-key: ENC(82RDh6TXLmQ+g5CNTGM+Uqr0KoP9nw8h5J8XcPTKjRWY7LIIIfa96aALEyzsSiu9yLu/O1ieFAKvfSIEdJxVIJCR0qki4lu7ocOf4naRSXR+bEVvdWTete1HoMgq2iFZ82ipGkcDjPvp4JwojC3Ac/5FlJdyIlbAcmNTus+031nmY5B/ECsBegPI/cecYFKzJDyYSibMsHvTM9lyswSpz0IqmghNIGNCPuweKsUD2uxxwKDYd7ndMpAed7ArRWDK8iY+Y9pz/lVQSptr6Bh4pg==)
      connection-timeout: 60s
      read-timeout: 60s
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7
          max-tokens: 2000

    anthropic:
      api-key: ENC(YdQvKv5zbYfDEynArpPc41G9s7HRgY1fuThtWVkgytszExwnzTBhKIK9VHLvogUrUF4KkHB+msqzfIO6KeJeSKPvIaRKds6dOAVIGz/6ifvb3WmrdL+ThEr/k9asCO/calUkQa5UMieEX0Saq3aDTG2U6XZzmfUtCT4pj/etwV2eXISIG2SE/afY1A++5kgZ)
      connection-timeout: 60s
      read-timeout: 60s
      chat:
        options:
          model: claude-sonnet-4-20250514
          temperature: 0.7
          max-tokens: 2000

    vertex:
      ai:
        gemini:
          project-id: study-app-472920
          location: us-central1
          credentials-uri: ${VERTEX_AI_CREDENTIALS_URI}
          transport: rest
          connection-timeout: 60s
          read-timeout: 60s
          write-timeout: 60s
          chat:
            options:
              model: gemini-1.5-flash
              temperature: 0.7
              max-output-tokens: 2000

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(xCYGXzxpsa9uKsbxzzLUw9UL14OAjxoHY90Z8a9NaeAFIfy+BEjIu6cc6LX76bk9Pz7M9lUPa+R2XAgVMI4x7hOJtJlinEL1dY5i2Pm4lu8JDapYeOYfq4IRsURGFBDZADglbMEPu13StHGGLUZ1uQ==)
            client-secret: ENC(Kqk4oUXL2347o3/P/TK/MKmtrZ74f66cTTW+q4wKgqPpEwNltFVvCobBhk7XPwHp3PoJU6dwzCLyDhyv56phXn9k2T8s3PKyYgDauA7EYgU=)
            scope:
              - openid
              - profile
              - email
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
          github:
            client-id: ENC(/fX1aEl7BdXRtpjJmXOl9c4Sofd9K/PCXYDl2RYOmSF7hK1BCHUkMoUC5AWt71jfh6QgDeV3EiyzqmW8AjWcLw==)
            client-secret: ENC(s4a5sTQ+Wkg/bTOpQ9HCXgWsnWuhIaAvbMlfJRASsa4h9lHqD0JSjzmwmiz9CGMHfVmUn5/YIr/O7vzHZTsaU1p3XNCLZa720BaI1uFAsqI=)
            scope:
              - user:email
              - read:user
            redirect-uri: "http://localhost:8080/login/oauth2/code/github"

server:
  port: 8080

logging:
  level:
    root: INFO
    com.flashcards.backend: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.security: DEBUG

jwt:
  secret: ENC(JyRDKsQ2KzyPru4MOH9aJNfrd84BazOmMZ77bae3I5dIlI53Zfks/qo6mRahBz+VG6/Dk55SPppIKtul+UxcZ1GRP8TTEPIqPc8IRzZRwOg=)
  expiration: 86400000  # 24 hours
  issuer: flashcards-app

oauth:
  success-redirect-url: http://localhost:3000/auth/success
  failure-redirect-url: http://localhost:3000/auth/error

jasypt:
  encryptor:
    password: xNWQql0Oy04Do+MqtJfPuB/hFEyo79X1Ehj0DKtQXm4=
    algorithm: PBEWITHHMACSHA512ANDAES_256
    key-obtention-iterations: 1000
    pool-size: 1
    provider-name: SunJCE
    salt-generator-class-name: org.jasypt.salt.RandomSaltGenerator
    iv-generator-class-name: org.jasypt.iv.RandomIvGenerator
    string-output-type: base64

admin:
  email: ${ADMIN_EMAIL}
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}
  first-name: ${ADMIN_FIRST_NAME}
  last-name: ${ADMIN_LAST_NAME}

ai:
  limits:
    max-flashcards-per-request: 20
    max-text-length: 10000
    rate-limit-per-minute: 10
  cache:
    enabled: true
    ttl: 3600
  fallback:
    enabled: true
    max-retries: 2
    fallback-models:
      - GPT_4O_MINI
      - CLAUDE_3_5_HAIKU
      - GEMINI_1_5_FLASH